/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAboutRouteImport } from './routes/_authenticated.about'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedCommunityRouteImport } from './routes/_authenticated.community'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated.help'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated.notifications'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as AuthenticatedAdminActivitiesRouteImport } from './routes/_authenticated.admin.activities'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated.admin.analytics'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated.admin.audit'
import { Route as AuthenticatedAdminDonorsRouteImport } from './routes/_authenticated.admin.donors'
import { Route as AuthenticatedAdminProposalsRouteImport } from './routes/_authenticated.admin.proposals'
import { Route as AuthenticatedAdminSbmRouteImport } from './routes/_authenticated.admin.sbm'
import { Route as AuthenticatedAdminSbuRouteImport } from './routes/_authenticated.admin.sbu'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated.admin.users'
import { Route as AuthenticatedCommunityIndexRouteImport } from './routes/_authenticated.community.index'
import { Route as AuthenticatedCommunitySlugRouteImport } from './routes/_authenticated.community.$slug'
import { Route as AuthenticatedProposalsIndexRouteImport } from './routes/_authenticated.proposals.index'
import { Route as AuthenticatedProposalsIdRouteImport } from './routes/_authenticated.proposals.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAboutRoute = AuthenticatedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCommunityRoute = AuthenticatedCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminActivitiesRoute =
  AuthenticatedAdminActivitiesRouteImport.update({
    id: '/activities',
    path: '/activities',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminDonorsRoute =
  AuthenticatedAdminDonorsRouteImport.update({
    id: '/donors',
    path: '/donors',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProposalsRoute =
  AuthenticatedAdminProposalsRouteImport.update({
    id: '/proposals',
    path: '/proposals',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSbmRoute = AuthenticatedAdminSbmRouteImport.update({
  id: '/sbm',
  path: '/sbm',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSbuRoute = AuthenticatedAdminSbuRouteImport.update({
  id: '/sbu',
  path: '/sbu',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedCommunityIndexRoute =
  AuthenticatedCommunityIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCommunityRoute,
  } as any)
const AuthenticatedCommunitySlugRoute =
  AuthenticatedCommunitySlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedCommunityRoute,
  } as any)
const AuthenticatedProposalsIndexRoute =
  AuthenticatedProposalsIndexRouteImport.update({
    id: '/proposals/',
    path: '/proposals/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProposalsIdRoute =
  AuthenticatedProposalsIdRouteImport.update({
    id: '/proposals/$id',
    path: '/proposals/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/about': typeof AuthenticatedAboutRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/community': typeof AuthenticatedCommunityRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/help': typeof AuthenticatedHelpRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/activities': typeof AuthenticatedAdminActivitiesRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/donors': typeof AuthenticatedAdminDonorsRoute
  '/admin/proposals': typeof AuthenticatedAdminProposalsRoute
  '/admin/sbm': typeof AuthenticatedAdminSbmRoute
  '/admin/sbu': typeof AuthenticatedAdminSbuRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/community/$slug': typeof AuthenticatedCommunitySlugRoute
  '/proposals/$id': typeof AuthenticatedProposalsIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/community/': typeof AuthenticatedCommunityIndexRoute
  '/proposals/': typeof AuthenticatedProposalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/about': typeof AuthenticatedAboutRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/help': typeof AuthenticatedHelpRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/activities': typeof AuthenticatedAdminActivitiesRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/donors': typeof AuthenticatedAdminDonorsRoute
  '/admin/proposals': typeof AuthenticatedAdminProposalsRoute
  '/admin/sbm': typeof AuthenticatedAdminSbmRoute
  '/admin/sbu': typeof AuthenticatedAdminSbuRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/community/$slug': typeof AuthenticatedCommunitySlugRoute
  '/proposals/$id': typeof AuthenticatedProposalsIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/community': typeof AuthenticatedCommunityIndexRoute
  '/proposals': typeof AuthenticatedProposalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/about': typeof AuthenticatedAboutRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/community': typeof AuthenticatedCommunityRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/admin/activities': typeof AuthenticatedAdminActivitiesRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/donors': typeof AuthenticatedAdminDonorsRoute
  '/_authenticated/admin/proposals': typeof AuthenticatedAdminProposalsRoute
  '/_authenticated/admin/sbm': typeof AuthenticatedAdminSbmRoute
  '/_authenticated/admin/sbu': typeof AuthenticatedAdminSbuRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/community/$slug': typeof AuthenticatedCommunitySlugRoute
  '/_authenticated/proposals/$id': typeof AuthenticatedProposalsIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/community/': typeof AuthenticatedCommunityIndexRoute
  '/_authenticated/proposals/': typeof AuthenticatedProposalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/about'
    | '/admin'
    | '/community'
    | '/dashboard'
    | '/help'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/admin/activities'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/donors'
    | '/admin/proposals'
    | '/admin/sbm'
    | '/admin/sbu'
    | '/admin/users'
    | '/community/$slug'
    | '/proposals/$id'
    | '/admin/'
    | '/community/'
    | '/proposals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/about'
    | '/dashboard'
    | '/help'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/admin/activities'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/donors'
    | '/admin/proposals'
    | '/admin/sbm'
    | '/admin/sbu'
    | '/admin/users'
    | '/community/$slug'
    | '/proposals/$id'
    | '/admin'
    | '/community'
    | '/proposals'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/about'
    | '/_authenticated/admin'
    | '/_authenticated/community'
    | '/_authenticated/dashboard'
    | '/_authenticated/help'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/admin/activities'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/donors'
    | '/_authenticated/admin/proposals'
    | '/_authenticated/admin/sbm'
    | '/_authenticated/admin/sbu'
    | '/_authenticated/admin/users'
    | '/_authenticated/community/$slug'
    | '/_authenticated/proposals/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/community/'
    | '/_authenticated/proposals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/about': {
      id: '/_authenticated/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/community': {
      id: '/_authenticated/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AuthenticatedCommunityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/activities': {
      id: '/_authenticated/admin/activities'
      path: '/activities'
      fullPath: '/admin/activities'
      preLoaderRoute: typeof AuthenticatedAdminActivitiesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/donors': {
      id: '/_authenticated/admin/donors'
      path: '/donors'
      fullPath: '/admin/donors'
      preLoaderRoute: typeof AuthenticatedAdminDonorsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/proposals': {
      id: '/_authenticated/admin/proposals'
      path: '/proposals'
      fullPath: '/admin/proposals'
      preLoaderRoute: typeof AuthenticatedAdminProposalsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sbm': {
      id: '/_authenticated/admin/sbm'
      path: '/sbm'
      fullPath: '/admin/sbm'
      preLoaderRoute: typeof AuthenticatedAdminSbmRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sbu': {
      id: '/_authenticated/admin/sbu'
      path: '/sbu'
      fullPath: '/admin/sbu'
      preLoaderRoute: typeof AuthenticatedAdminSbuRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/community/': {
      id: '/_authenticated/community/'
      path: '/'
      fullPath: '/community/'
      preLoaderRoute: typeof AuthenticatedCommunityIndexRouteImport
      parentRoute: typeof AuthenticatedCommunityRoute
    }
    '/_authenticated/community/$slug': {
      id: '/_authenticated/community/$slug'
      path: '/$slug'
      fullPath: '/community/$slug'
      preLoaderRoute: typeof AuthenticatedCommunitySlugRouteImport
      parentRoute: typeof AuthenticatedCommunityRoute
    }
    '/_authenticated/proposals/': {
      id: '/_authenticated/proposals/'
      path: '/proposals'
      fullPath: '/proposals/'
      preLoaderRoute: typeof AuthenticatedProposalsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/proposals/$id': {
      id: '/_authenticated/proposals/$id'
      path: '/proposals/$id'
      fullPath: '/proposals/$id'
      preLoaderRoute: typeof AuthenticatedProposalsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminActivitiesRoute: typeof AuthenticatedAdminActivitiesRoute
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminDonorsRoute: typeof AuthenticatedAdminDonorsRoute
  AuthenticatedAdminProposalsRoute: typeof AuthenticatedAdminProposalsRoute
  AuthenticatedAdminSbmRoute: typeof AuthenticatedAdminSbmRoute
  AuthenticatedAdminSbuRoute: typeof AuthenticatedAdminSbuRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminActivitiesRoute: AuthenticatedAdminActivitiesRoute,
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminDonorsRoute: AuthenticatedAdminDonorsRoute,
  AuthenticatedAdminProposalsRoute: AuthenticatedAdminProposalsRoute,
  AuthenticatedAdminSbmRoute: AuthenticatedAdminSbmRoute,
  AuthenticatedAdminSbuRoute: AuthenticatedAdminSbuRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedCommunityRouteChildren {
  AuthenticatedCommunitySlugRoute: typeof AuthenticatedCommunitySlugRoute
  AuthenticatedCommunityIndexRoute: typeof AuthenticatedCommunityIndexRoute
}

const AuthenticatedCommunityRouteChildren: AuthenticatedCommunityRouteChildren =
  {
    AuthenticatedCommunitySlugRoute: AuthenticatedCommunitySlugRoute,
    AuthenticatedCommunityIndexRoute: AuthenticatedCommunityIndexRoute,
  }

const AuthenticatedCommunityRouteWithChildren =
  AuthenticatedCommunityRoute._addFileChildren(
    AuthenticatedCommunityRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAboutRoute: typeof AuthenticatedAboutRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCommunityRoute: typeof AuthenticatedCommunityRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedProposalsIdRoute: typeof AuthenticatedProposalsIdRoute
  AuthenticatedProposalsIndexRoute: typeof AuthenticatedProposalsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAboutRoute: AuthenticatedAboutRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCommunityRoute: AuthenticatedCommunityRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedProposalsIdRoute: AuthenticatedProposalsIdRoute,
  AuthenticatedProposalsIndexRoute: AuthenticatedProposalsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
